version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  test-cloudformations:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: cf-test
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          configure-default-region: true
      - run:
          name: Validating CloudFormation code 
          command: | 
            echo "Validating all templates in the ${HOME}/project/products directory..."
            for template in `ls ${HOME}/project/products/*yml`
            do
              echo "Validating CloudFormation template: $template"
              aws cloudformation validate-template --template-body file:///$template
            done

            echo "Validating all templates in the ${HOME}/project/service_catalog directory..."
            for template in `ls ${HOME}/project/service_catalog/*yml`
            do
              echo "Validating CloudFormation template: $template"
              aws cloudformation validate-template --template-body file:///$template
            done

  update-templates:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: cf-test
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          configure-default-region: true
      - run:
          name: Deploy product templates
          command: | 
            echo "Copying all product templates to the s3 bucket responsible for hosting the templates."
            aws s3 cp ${HOME}/project/products s3://${PRODUCT_S3_BUCKET}/ --recursive --exclude "*" --include "*.yml"
            

         

workflows:
  version: 2
  aws-cli:
    jobs:
      - test-cloudformations
      - update-templates:
          filters:
            branches:
              only:
                # This is the list of branches which will trigger a terraform run.
                - master   
          requires:
            - test-cloudformations                     